version: '2'
services:
  hexo:
    restart: always
    build:
        context: hexo
    container_name: hexo
    ports:
      - "4000:4000"
    volumes:
     - $HOME/.ssh:/root/.ssh
     - $PWD/source:/hexo/source
     - $PWD/themes:/hexo/themes
     - $PWD/_config.yml:/hexo/_config.yml
    environment:
     - GIT_USER_NAME=alshin
     - GIT_USER_EMAIL=alshin@126.com